# 01 Meu TensorFlow (TF) Intro ao Básico
+ Aulas do Curso
 - 1. TD Basic Syntax (Seesion : onde pode fazer operaçoes)
 - 2. TF Graphs
 - 3. TF Variabels And PlaceHoldeers
Tópicos
+ s (defniri quais funçêos sao mencionadas em ordem e o que fzaer [por num md separado como meu cheatsehet em PRIVATE]

In [1]:
import tensorflow as tf

In [2]:
# Para sabe a versão do tensor Flow
print(tf.__version__)

1.3.0


## Tensor
+ Objetos 'Tensor' não são printáveis
+ Para podemros manipulálas melhor, temos que criar uma seção
+ Em `tf.constant` estamos criado objetos Tensor que são constantes

### TF com String

In [5]:
# Aqui estamos criando Tesnor, pode ser String ou número
hello = tf.constant("Hello ")
world = tf.constant('World')
# print do tipo
print(str(type(hello)))

<class 'tensorflow.python.framework.ops.Tensor'>


In [7]:
# A sesão fecah atutomaticmamten
with tf.Session() as sess:
    # Aqi dentro, doradremos operações no Tensor
    result = sess.run(hello + world)
    
print(result, str(type(result))) # result é represenado em bytes 'b'

b'Hello World' <class 'bytes'>


### TF Com número

In [8]:
a = tf.constant(10)
b = tf.constant(20)
print(a+b) # não é algo printável
# para  rodar, temos que rodar sobre umaa seção

Tensor("add_2:0", shape=(), dtype=int32)


In [10]:
with tf.Session() as sess:
    result_number = sess.run(a+b)
print(result_number, str(type(result_number)))

30 <class 'numpy.int32'>


### TF Constante com matriz

In [21]:
# tf.fill(dims, value, name=None)
#    Creates a tensor filled with a scalar value.
const = tf.constant(10)
fill_mat = tf.fill( (2,2), 10) # cria matriz com número 10
my_zeros = tf.zeros( (3,3)) # cria matriz de zeros
my_ones  = tf.ones( (2,2)) # cria matriz de uns

In [22]:
# tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
# @shape = tupla que define as dimensões
# @mean = o valor de médai da trsitribuição, o ponto do chapeu
# @sttdev = desvio padrao
my_rand_n = tf.random_normal((3,3),mean=0,stddev=0.5)

In [26]:
# tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
# OBS: por default o range é [0, 1), 
# OBS: Se usar o tipo inteiro em @dtype : tem que especificar o maxval
my_rand_u = tf.random_uniform( (2,2), minval = 0, maxval = 1)

#### Sessâo interativa (Only notebook)
Para executar, estavamos usando o `with` com TF.Session. Porém, podemos usar de forma interativa a sessão comc `tf.IntercativeSeession()`. 

Usando sobre a variavel que o carrea, poderá ler dados de outras células

OBS: Mas em geral vamos usar com `with` mesmo

**Vantagem** : Depois de criala numa célula, voce pode usar nas outras. Isso é vatanjoso pois **nao dá para fazer o mesmo com `with`**

In [28]:
# executando sobre a lista
my_ops = [const, fill_mat, my_zeros, my_ones, my_rand_n, my_rand_u]
# criando a sessao interativa, 
#depois de declarada, voce pode usar em outras células
interactive_sess = tf.InteractiveSession()
# executando
for op in my_ops:
    #print(interactive_sess.run(op))
    print(op.eval())
# OBS: voce pode ter o meso resultado se executar: op.eval()

10
[[10 10]
 [10 10]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 0.353706   -0.4491896   1.07840598]
 [-0.49988946 -0.33969015  0.67270929]
 [-0.03861309  0.43721312 -0.55777895]]
[[ 0.86420643  0.35081518]
 [ 0.84387434  0.6960777 ]]


### TF com Matriz

In [32]:
a_array = tf.constant([ [1,2],
                        [3,4] ])
b_array = tf.constant( [ [1], [100] ])

In [33]:
# Recuperando o tamanho
a_array.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [35]:
# multiplicação de matrizes : é o somatorio de multiplicações para matriz
result = tf.matmul(a_array, b_array)
interactive_sess.run(result)

# array([[201],  <== (1*1) + (2*100)
#       [403]])  <== (3*1) + (4*100)

# poedemos tambem executar
# result.eval()

array([[201],
       [403]])

# 2. TF Graps (video-aula)

#### Grafos
+ Conjutos de node/vertice  ligados por arestas/edges
+ Em TF, cada node é uma operação que tem uma possivel entrada e saida

#### Grafos no TensorFlow
Por padrão há sempre um grafo `tf.get_default_graph()`


![Imagem de nodes](C:\Users\Rafael\Google Drive\Private Studies\Computer Advanced\udemy-jose-padilla-tensorflow\imgs\img16.png)

In [38]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [39]:
print(tf.get_default_graph())

In [40]:
g = tf.Graph() # criando um novo grafo
print(g) # printando, veja que sera difrente do get_default

In [41]:
graph_one = tf.get_default_graph() # obviamente sera referenciado a o grafo default
print(graph_one)

Percabe que `default_graph` é sempre o mesmo, mesmo que voce cri outro
Para mudar isso temos que usar ` wiht #Grapgh.as_default`
OBS: Perceba entâo que esse novo grafo default só serve dentro do bloco

In [43]:
graph_two = tf.Graph()
with graph_two.as_default():
    print(graph_two is tf.get_default_graph()) # true, pois acabamos de definir que o defualt serai graph_two
graph_two is tf.get_default_graph() # false, pois saiu do 'with' o default voltou a ser o primeiro a ser cirado

True


Esses concentios e´so pra entender que já se ttrabalha automaticamente num grafo e que, pode ser necessário resetar. Entâo, vimos como fazer isso, criando outro gráfo

Isso tembem é util em notebooks

# 3. Variabels And Placeholder (aula3)
Relembrando:

**Variables**: Pesos e Viés. Presisam ser inicializados

**PlaceHolders**: sâo campos onde serao posto os dados para treinar, nao presisa declarar nada especifico exceto se for tf.float32; povoce pode escolher o `shape` como argumento

In [48]:
# caso nao tiver definido
sess = tf.InteractiveSession()

In [49]:
my_tensor = tf.random_uniform( (4,4), 0, 1)
my_tensor

<tf.Tensor 'random_uniform_5:0' shape=(4, 4) dtype=float32>

### Variables

Ao ler tudo, perceba que em grande parte, so vai presisar  do initial value que é um `Tensor`
````
tf.Variable(
    initial_value=None,   ==> Recebe um `Tensor` que define o `shape` e tipo de dados. Após iniciadlizado, esse tipo e                                          shape ficaão fixo. Se quiser mudar deppis, tem que mudar validate_shape para FALSE
    trainable=True, 
    collections=None, 
    validate_shape=True,  ==> se podera ou nao mudar de shape apos definido
    caching_device=None, 
    name=None,            ==> Um nome identiticado, por default pega 'Variable'quando nao tem
                                variable_def=None, 
    dtype=None,           ==> o tipo de dado, ja é desidio em initial_value, mas ao colocaos podera fazer com que o TF convertea                                os dados quando possivel para esse tipo
    expected_shape=None,  ==> se colocado m shape (tupla) vai espserr que o que seja inserido seja desse shape
    import_scope=None)
````

In [50]:
my_var = tf.Variable(initial_value = my_tensor) # Definido
# sess.run(my_var) # nao vai funcionar pois a variavael nao foi inicializada

In [51]:
# A inicializaçã de uma variável tem que ser feita a partir de um método, 
# nao é simplisemnte cria uma var que vai armazenar seu endereço criado
init = tf.global_variables_initializer()
sess.run(init) # vai inicializar as variaveis criadas
# so depois de fazer isso vai dar para printar uma variable
sess.run(my_var)

array([[ 0.35261488,  0.48229396,  0.49794829,  0.70775855],
       [ 0.13841283,  0.08721912,  0.11391294,  0.34744167],
       [ 0.96103311,  0.80230868,  0.67418063,  0.72516882],
       [ 0.01028752,  0.48391187,  0.83339047,  0.40215969]], dtype=float32)

### PlaceHolders

In [52]:
# tf.placeholder(dtype, shape=None, name=None)
# @shape => nao é obrigado, ja que so estamos inicializando o 'recipiente vazio'
#   OBs: mutias vezes usa 'none' no shape, tem um motivo pra iso busque saber
ph = tf.placeholder(dtype = tf.float32, shape = (None, 5))