# Numpy
## Parte 1

In [27]:
## Aqui, criamos um array do numpy apartir da nossa lsita
my_list = [10,20,30]
np.array(my_list)

array([10, 20, 30])

In [25]:
## Primeiro, temos que importálo para usálo
## em geral, se convenciona ter um 'as' para dar um apelido a lib pra usala
##     numpy = np (convensao, mas pod ser qualuq2er coisa)
## 
import numpy as np

In [4]:
## matriz, lista de lista
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
## np.arange = cria sequencia de numeros
## SHIFT+TAB : presia de inicio e fim, (o final nao entra), tem tambem um parametro adiconal de step
np.arange(2,19,3)

array([ 2,  5,  8, 11, 14, 17])

In [9]:
## np.zeros(qtd) = criat vetor de zeros
arrZero = np.zeros(7)
arrZero

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
## Posso produzir matrix passadno tupla
matrixZeros = np.zeros((4,5))
matrixZeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
## np.ones = preenche com 1 em vez de 0
arrayOne = np.ones(7)
arrayOne

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
## np.eye = cria matriz identidade (diagonal == 1 ), ela é quadrado por definiçao 
## voce passa como pram o tamnho do quadrado
matrixIdentity = np.eye(3)
matrixIdentity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## np.linspace(start,end,numer_in_midlle) = semelahnte ao arange, ele mostra uma serie que vai de inicio e inclui o fim
## a diferença eh que o 3@ especifica QUANTOS NUMEROS VOCE QUER VEM DE FORMA ESPEACAÇADOS
print(np.linspace(0,10,2)) 
print(np.linspace(0,10,3)) 
print(np.linspace(0,10,4))
print(np.linspace(0,10,5))

[ 0. 10.]
[ 0.  5. 10.]
[ 0.          3.33333333  6.66666667 10.        ]
[ 0.   2.5  5.   7.5 10. ]


In [15]:
## np.random = sub-lib pra gerar numeros aleartorios

In [16]:
## np.random.rand() = retorna um numero random de [0,1]
##      Tirados de uma distriuiçâo uniiforme, onde ha possibilidade igaul de sair qualquer numero para todos
##     parametros: especifica a saida, se for um paramtro, é um vetor dessa quantidade
##     2 paramtrow>: sera uma mastriz na dimesnsao passada
np.random.rand(5)

array([0.00703936, 0.84780886, 0.51358174, 0.65956927, 0.62562208])

In [17]:
np.random.rand(3,3,3)

array([[[0.13419641, 0.11391518, 0.06291714],
        [0.80424466, 0.1035132 , 0.76612741],
        [0.17994749, 0.74477292, 0.73418912]],

       [[0.59122366, 0.52306369, 0.39949563],
        [0.01698954, 0.53006145, 0.46176625],
        [0.76930775, 0.36625947, 0.20538256]],

       [[0.08436362, 0.27461017, 0.09622976],
        [0.54902139, 0.25164245, 0.04071624],
        [0.56200766, 0.63412792, 0.28064512]]])

In [18]:
## np.random.randn() = de uma distribuiçao normal
## distribuiçao nromal eh mais util na vida real que a uniforme
np.random.randn(4)

array([-0.0230813 , -0.03928745, -0.59765968,  1.46540479])

In [19]:
##np.random.randint() = tira da uniforme agora numeros inteiro a partir de um intervalo
##      (star,end, qtd de numeros), end nao esta incluso
np.random.randint(0,100,10)

array([90, 60, 73, 15,  6, 65, 11, 76, 81, 19])

In [20]:
## np.round() = arredaonda um aray passadopara uma certa qtd de casa decimais
np.round(np.random.rand(4)*100, 0)

array([62., 61., 51., 63.])

In [21]:
## np.reshape
##    converte formato, tipo, um vetor de 25 elementos numa matriz 5 por 5
arr = np.random.rand(25)
print(arr)
## para matriz de 5 linhas e 5 colunas
arr = arr.reshape((5,5))
print(arr)

[0.59556921 0.19903449 0.2642278  0.35188599 0.15536669 0.49212494
 0.51214724 0.72745968 0.21394668 0.7736883  0.01354335 0.57863387
 0.57988762 0.26418313 0.75722151 0.30953269 0.17140516 0.76292459
 0.76978946 0.71024942 0.82002359 0.6163652  0.04003351 0.98767882
 0.80643254]
[[0.59556921 0.19903449 0.2642278  0.35188599 0.15536669]
 [0.49212494 0.51214724 0.72745968 0.21394668 0.7736883 ]
 [0.01354335 0.57863387 0.57988762 0.26418313 0.75722151]
 [0.30953269 0.17140516 0.76292459 0.76978946 0.71024942]
 [0.82002359 0.6163652  0.04003351 0.98767882 0.80643254]]


In [22]:
## [array].shape = shape do array
## perceba que issonao eh um metodo, eh um atributo do objeto array
##     perceba que nao usop parentesis
arr.shape

(5, 5)

In [24]:
print('arr.max() = ',arr.max()) #maior elementos
print('arr.min() = ',arr.min()) ## menor elementos
print('arr.argmax() = ', arr.argmax()) # indeice do maior
print('arr.argmin() = ', arr.argmin()) #indice do menor

arr.max() =  0.9876788183706633
arr.min() =  0.013543345804381213
arr.argmax() =  23
arr.argmin() =  10


## Parte 2
Estudaremos método para puxar informaçoes relevantes de nossos arrays

In [30]:
myArray = np.arange(0,30,3) ## de 0 a 30 de 3 em 3
myArray

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [31]:
## Puxar subconjuto de array
## utilizamos ':", indexaçao que começa de [0] 
## inclui inicio mas nao o fim
myArray[3:6] [3],[4][5]

array([ 9, 12, 15])

In [32]:
## aqui o python entedne que estou puxando a partir do zero
myArray[:5] #sem incluir o [5] = 6 elemento

array([ 0,  3,  6,  9, 12])

In [33]:
## agora definimos um start sem end
myArray[6:]

array([18, 21, 24, 27])

Essas mesma operaçoes sao uteis para tambem atribuir ou aplicar algo em parte desse aray

In [34]:
## Novos atribuiçao ao array
myArray = np.arange(50).reshape(5,10)

In [35]:
myArray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
## slice = fatias
## primeiro colchete faz mençao a linha e o segundo a coluna
myArray[:3][:] ## linha: pegar de [0] ate [3] = [2 sem incluilo]
                ## coluna: pegar todas as colunas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**CUDIADO, Ao fazer atribuiçao com ARRAY**

** array() é um objeto, como tal, se voce falar que arr2 = arr significa que voce esta dizendo que arr aponta para o que apointa arr, assim, se voce modificar qualquer um deles, vai modidificar os dois, pois os dois estao apontando para um mesmo luugar**

** Para evitar isso, utilize `.copy` para criar um novo objeto e assim atribuilo**

In [37]:
myArr = np.arange(30).reshape((10,3))
myArr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [40]:
myArr2 = myArr[0:2][0:6]
myArr2

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
myArr2[:] = 100
myArr2

array([[100, 100, 100],
       [100, 100, 100]])

In [42]:
myArr

array([[100, 100, 100],
       [100, 100, 100],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29]])

**Perceba**: myArr2 pegou parter do myArr e mudou, mas myArr no final tambem mudou, isso por que os dois estao apontando para um objeto na memoria, se voce quiser separr, tem que usar ``.copy`

In [45]:
myArr2 = myArr[0:2][0:6].copy()
myArr2[:] = 50
myArr2

array([[50, 50, 50],
       [50, 50, 50]])

In [46]:
myArr

array([[100, 100, 100],
       [100, 100, 100],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29]])

**Usando `.copy()` nao mudou para 50**

### Operações Lógicas com Array

In [47]:
## temos esse array
myArray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
## Ao aplciar uma iopreçao lógica sobre o array, ele automaticamente a aplcia para todos os elemtntos
## vai retornar um array de mesmo shape de bools
myArray > 30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [49]:
## esse array de bools é útil para o slice
## cm ele, voce pode entao dar um slice apartir desse ArrayDeBools e asism extrati somente dados que satisfaça essa caondiçao dada
## FUNCIONA desde que o shape seja o mesmo
arrayBool = myArray > 20
arrayBool 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [50]:
##Extraindo somente onde foi tru
## Voce psass como argumetno um arary de bools
myArray[arrayBool]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### Parte 3 - Operaçoes com rrays em NumPy

In [54]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Operaçoes entre arrays

In [57]:
## Soma de arrays = se os dois forem array somea elemtnot por elemetno
## Os dois tem que ter a mesma forma
## da mesma forma da para  fazer (-), (*), ?(/), ()
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [56]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

Operações com escalares
+ Aplicada a todos os elmetnos no array

In [58]:
## Da certo tambem
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
arr + 111

array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125, 126])

In [60]:
arr * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

#### Operaçoes para array pelo numPy
+ Tem que usar a lib

In [61]:
## raiz quadrado
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [62]:
## expoenciaçao
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [63]:
## np.mean(in_array) =  Media aritmetica
np.mean(arr)

7.5

In [64]:
## np.std(in_array) = desvio padrao
np.std(arr)

4.6097722286464435

In [65]:
## aplciar seno 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

[link com funçoes universais e doc](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)